#!/usr/bin/env python3
"""Synthesizes assets/audio/music.mp3 and assets/audio/sfx.mp3 from scratch.

Everything is generated by this script (no samples, no third party material),
so there are no copyright or licensing constraints on the result.

Usage: python3 src/make_audio.py   (needs numpy and ffmpeg)
Cue times come from src/cues.json (written by src/build.mjs).
"""
import json
import subprocess
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "audio"
OUT.mkdir(parents=True, exist_ok=True)
SR = 44100
rng = np.random.default_rng(7)  # fixed seed: identical output on every run

cues = json.loads((ROOT / "src" / "cues.json").read_text())
TOTAL = float(cues["total"])
N = int(TOTAL * SR)


def mtof(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def env_adsr(n, a, d, s, r):
    """Attack, decay to sustain level s, release; n samples."""
    e = np.ones(n)
    na, nd, nr = int(a * SR), int(d * SR), int(r * SR)
    na = min(na, n)
    e[:na] = np.linspace(0, 1, na, endpoint=False) if na else e[:0]
    nd = min(nd, n - na)
    if nd > 0:
        e[na:na + nd] = np.linspace(1, s, nd)
    e[na + nd:] = s
    nr = min(nr, n)
    if nr > 0:
        e[-nr:] *= np.linspace(1, 0, nr)
    return e


def add(buf, start, sig, pan=0.0, gain=1.0):
    """Mix mono sig into stereo buf at time start (s). pan -1..1."""
    i = int(start * SR)
    if i >= buf.shape[0] or i < 0:
        return
    n = min(len(sig), buf.shape[0] - i)
    l = gain * np.sqrt((1 - pan) / 2)
    r = gain * np.sqrt((1 + pan) / 2)
    buf[i:i + n, 0] += sig[:n] * l
    buf[i:i + n, 1] += sig[:n] * r


def tone(freq, dur, harmonics=((1, 1.0),), detune_cents=0.0):
    t = np.arange(int(dur * SR)) / SR
    f = freq * 2 ** (detune_cents / 1200)
    sig = np.zeros_like(t)
    for h, a in harmonics:
        sig += a * np.sin(2 * np.pi * f * h * t)
    return sig


def lowpass(x, cutoff):
    """One pole lowpass, scalar cutoff in Hz."""
    a = np.exp(-2 * np.pi * cutoff / SR)
    y = np.empty_like(x)
    acc = 0.0
    for i, v in enumerate(x):
        acc = (1 - a) * v + a * acc
        y[i] = acc
    return y


def reverb(stereo, wet=0.22, seconds=2.2):
    n = int(seconds * SR)
    t = np.arange(n) / SR
    out = np.zeros_like(stereo)
    for ch in range(2):
        ir = rng.standard_normal(n) * np.exp(-t * 3.2)
        ir = lowpass(ir, 4500)
        ir /= np.sqrt(np.sum(ir ** 2))
        size = stereo.shape[0] + n
        fsize = 1 << (size - 1).bit_length()
        conv = np.fft.irfft(np.fft.rfft(stereo[:, ch], fsize) * np.fft.rfft(ir, fsize), fsize)[: stereo.shape[0]]
        out[:, ch] = conv
    return stereo * (1 - wet * 0.5) + out * wet


# ---------------------------------------------------------------------------
# Music: C - G - Am - F, 100 BPM, one chord per bar
# ---------------------------------------------------------------------------
BPM = 100
BEAT = 60.0 / BPM
BAR = 4 * BEAT
CHORDS = [
    ([60, 64, 67, 72], 36),  # C
    ([59, 62, 67, 71], 43),  # G
    ([60, 64, 69, 72], 45),  # Am
    ([60, 65, 69, 72], 41),  # F
]


def level(t, points):
    """Piecewise linear gain curve. points: [(time, gain), ...]."""
    xs, ys = zip(*points)
    return float(np.interp(t, xs, ys))


music = np.zeros((N, 2))
bars = int(np.ceil(TOTAL / BAR)) + 1
pad_curve = [(0, 0.0), (1.5, 0.55), (6, 0.5), (9, 0.75), (28, 0.9), (38, 1.0), (45, 0.8), (50, 0.9), (55, 0.0)]
pluck_curve = [(0, 0.0), (1.2, 0.35), (6.5, 0.0), (8.8, 0.0), (9.5, 0.8), (28, 1.0), (38, 1.1), (45, 0.8), (50, 0.5), (55, 0.0)]

for b in range(bars):
    t0 = b * BAR
    if t0 >= TOTAL:
        break
    notes, bass = CHORDS[b % 4]
    # pad: soft sustained chord with slow attack, slightly detuned pair per note for width
    for k, m in enumerate(notes[:3]):
        for det, pan in ((-4, -0.5), (4, 0.5)):
            sig = tone(mtof(m), BAR + 0.9, ((1, 1.0), (2, 0.25), (3, 0.08)), det)
            sig *= env_adsr(len(sig), 0.7, 0.4, 0.8, 0.9)
            add(music, t0, sig, pan, 0.045 * level(t0, pad_curve))
    # bass: beat 1 and beat 3 (from 9s)
    if t0 >= 9 and t0 < 50:
        for beat in (0, 2):
            ts = t0 + beat * BEAT
            sig = tone(mtof(bass), BEAT * 1.8, ((1, 1.0), (2, 0.2)))
            sig *= env_adsr(len(sig), 0.01, 0.3, 0.5, 0.4)
            add(music, ts, sig, 0.0, 0.17)
    # pluck arpeggio: quarters while sparse, eighths later
    pattern = [0, 1, 2, 3, 2, 1, 2, 1]  # chord tone indices
    step = BEAT if (t0 < 9 or t0 >= 46) else BEAT / 2
    steps = int(round(BAR / step))
    for i in range(steps):
        ts = t0 + i * step
        if ts >= TOTAL:
            break
        g = level(ts, pluck_curve)
        if g <= 0.01:
            continue
        m = notes[pattern[i % len(pattern)] % len(notes)]
        if ts >= 28 and ts < 46 and i % 4 == 2:
            m += 12  # sparkle an octave up in the build
        dur = 0.9
        sig = tone(mtof(m), dur, ((1, 1.0), (2, 0.35), (3, 0.12), (4, 0.05)))
        t = np.arange(len(sig)) / SR
        sig *= np.exp(-t / 0.22) * (1 - np.exp(-t / 0.004))
        add(music, ts, sig, -0.45 if i % 2 == 0 else 0.45, 0.115 * g)
    # soft shaker on off beats between 9s and 46s
    if 9 <= t0 < 46:
        for i in range(8):
            ts = t0 + i * BEAT / 2 + (BEAT / 2 if False else 0)
            if i % 2 == 1:
                n = int(0.05 * SR)
                nz = rng.standard_normal(n)
                nz = nz - lowpass(nz, 5000)  # crude highpass
                nz *= np.exp(-np.arange(n) / SR / 0.012)
                add(music, ts, nz, 0.25, 0.028)
    # very soft kick from 28s to 46s
    if 28 <= t0 < 46:
        for beat in (0, 2):
            ts = t0 + beat * BEAT
            n = int(0.35 * SR)
            t = np.arange(n) / SR
            f = 50 + 60 * np.exp(-t / 0.05)
            sig = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.12)
            add(music, ts, sig, 0.0, 0.16)

# final resolving chord at the closing card (C major add9), long ring out
tf = cues["swell"][0] + 0.2
for m, g in ((48, 1.0), (60, 0.9), (64, 0.8), (67, 0.8), (72, 0.6), (74, 0.4)):
    sig = tone(mtof(m), TOTAL - tf, ((1, 1.0), (2, 0.2), (3, 0.06)))
    sig *= env_adsr(len(sig), 0.5, 1.5, 0.55, 2.5)
    add(music, tf, sig, 0.0, 0.05 * g)

music = reverb(music, wet=0.28)
fade = np.ones(N)
fi, fo = int(1.2 * SR), int(3.2 * SR)
fade[:fi] = np.linspace(0, 1, fi)
fade[-fo:] = np.linspace(1, 0, fo) ** 1.5
music *= fade[:, None]


# ---------------------------------------------------------------------------
# SFX (very gentle)
# ---------------------------------------------------------------------------
sfx = np.zeros((N, 2))


def whoosh(t0):
    n = int(0.55 * SR)
    nz = rng.standard_normal(n)
    out = np.empty(n)
    acc = 0.0
    for i in range(n):
        p = i / n
        cutoff = 250 + 2600 * np.sin(np.pi * p) ** 2
        a = np.exp(-2 * np.pi * cutoff / SR)
        acc = (1 - a) * nz[i] + a * acc
        out[i] = acc
    out *= np.sin(np.pi * np.linspace(0, 1, n)) ** 2
    add(sfx, t0, out, 0.0, 0.55)


def pop(t0):
    n = int(0.12 * SR)
    t = np.arange(n) / SR
    f = 300 + 500 * np.exp(-t / 0.02)
    sig = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.035)
    add(sfx, t0, sig, 0.0, 0.32)


def click(t0):
    n = int(0.05 * SR)
    t = np.arange(n) / SR
    nz = rng.standard_normal(n)
    nz = nz - lowpass(nz, 1500)
    sig = nz * np.exp(-t / 0.006) * 0.8 + np.sin(2 * np.pi * 1900 * t) * np.exp(-t / 0.012) * 0.5
    add(sfx, t0, sig, 0.0, 0.28)


def ding(t0, i):
    f = 880 * (1.0595 ** (2 * i))
    sig = tone(f, 0.7, ((1, 1.0), (2, 0.3), (3, 0.08)))
    t = np.arange(len(sig)) / SR
    sig *= np.exp(-t / 0.18) * (1 - np.exp(-t / 0.003))
    add(sfx, t0, sig, 0.0, 0.22)


def tick(t0):
    n = int(0.03 * SR)
    t = np.arange(n) / SR
    sig = np.sin(2 * np.pi * 2300 * t) * np.exp(-t / 0.006)
    add(sfx, t0, sig, 0.0, 0.14)


def star_tick(t0):
    sig = tone(3200, 0.15, ((1, 1.0), (2, 0.2)))
    t = np.arange(len(sig)) / SR
    sig *= np.exp(-t / 0.03)
    add(sfx, t0, sig, 0.0, 0.1)


def thud(t0):
    n = int(0.45 * SR)
    t = np.arange(n) / SR
    f = 55 + 45 * np.exp(-t / 0.06)
    sig = np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t / 0.14)
    add(sfx, t0, sig, 0.0, 0.5)


def chime(t0, i):
    f = [1046.5, 1174.7, 1318.5, 1568.0, 1760.0, 2093.0][i % 6]
    sig = tone(f, 1.1, ((1, 1.0), (2.76, 0.25), (5.4, 0.08)))
    t = np.arange(len(sig)) / SR
    sig *= np.exp(-t / 0.28) * (1 - np.exp(-t / 0.003))
    add(sfx, t0, sig, 0.0, 0.12)


def swell(t0):
    for m in (72, 76, 79):
        sig = tone(mtof(m), 2.6, ((1, 1.0), (2, 0.15)))
        sig *= env_adsr(len(sig), 1.0, 0.8, 0.4, 1.4)
        add(sfx, t0, sig, 0.0, 0.05)


for t in cues["whoosh"]:
    whoosh(t - 0.05)
for t in cues["pop"]:
    pop(t)
for t in cues["click"]:
    click(t)
for i, t in enumerate(cues["ding"]):
    ding(t, i)
for t in cues["tick"]:
    tick(t)
for t in cues["starTick"]:
    star_tick(t)
for t in cues["thud"]:
    thud(t)
for i, t in enumerate(cues["chime"]):
    chime(t, i)
for t in cues["swell"]:
    swell(t)
sfx = reverb(sfx, wet=0.12, seconds=1.2)


def write_wav(path, data, peak=0.89):
    m = np.max(np.abs(data))
    if m > 0:
        data = data / m * peak
    pcm = (np.clip(data, -1, 1) * 32767).astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


tmp_m = OUT / "_music.wav"
tmp_s = OUT / "_sfx.wav"
write_wav(tmp_m, music)
write_wav(tmp_s, sfx, peak=0.7)


def encode(src, dst, loud):
    flt = f"loudnorm=I={loud}:TP=-1.5:LRA=7" if loud is not None else "anull"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(src), "-af", flt, "-ar", "44100", "-c:a", "libmp3lame", "-b:a", "192k", str(dst)],
        check=True,
    )


# music sits at about -19 LUFS alone; with the sfx on top the whole video lands near -17
encode(tmp_m, OUT / "music.mp3", -19)
encode(tmp_s, OUT / "sfx.mp3", None)
tmp_m.unlink()
tmp_s.unlink()
print("wrote", OUT / "music.mp3", OUT / "sfx.mp3")
